server:
  port: 9191

spring:
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 180000
    cache-names: userTokenCache
  redis:
    host: api-redis
    port: 6379

uri:
  expense-tracker: http://expense-tracker-backend:8181
  dummy-server: http://dummy-server-backend:5000

api:
  throttling:
    users:
      user-id-1:
        request-rate: 5
        interval: 2m
      user-id-2:
        request-rate: 2
        interval: 10s
  auth:
    protected-mapping: /api/**
    username: admin
    password: admin
    role: ADMIN
