server:
  port: 9191

spring:
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 180000
    cache-names: userTokenCache
  redis:
    host: localhost
    port: 6379

uri:
  expense-tracker: http://localhost:8181
  dummy-server: http://localhost:5000

api:
  throttling:
    users:
      user-id-1:
        request-rate: 5
        interval: 1m
      user-id-2:
        request-rate: 2
        interval: 10s
  auth:
    protected-mapping: /api/**
    username: et-user
    password: et-password
    role: USER
