server:
  port: 9191

uri:
  expense-tracker: http://localhost:8181
  dummy-server: http://localhost:5000

api:
  auth:
    protected-mapping: /api/**
    username: et-user
    password: et-password
    role: USER
